trigger:
- main
- feature/*

pr:
- main
- feature/*

jobs:
- job: Build
  steps:
  - script: echo Building...
    displayName: 'Run build'
  
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Pipeline'
